trigger: none
pr: none

pool:
  name: 'Azure Pipelines'

variables:
  node_version: '20.x'
  buildConfiguration: 'Release'
  angular_project_path: 'Web/Apps/StoreApp.Angular'

steps:
  - task: UseNode@1
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '$(node_version)'

  - script: |
      echo "Current working directory:"
      pwd
      echo "Listing contents:"
      ls -la
    displayName: 'Debug working directory'

  - script: |
      cd $(angular_project_path)
      echo "Cleaning npm cache..."
      npm cache clean --force
      echo "Removing node_modules if exist..."
      rm -rf node_modules
      echo "Installing npm packages..."
      npm install
    displayName: 'Clean install npm packages'

  - script: |
      cd $(angular_project_path)
      npm run build -- --configuration production
    displayName: 'Build Angular app'

  - task: CmdLine@2
    displayName: 'List dist contents'
    inputs:
      script: |
        ls -R $(angular_project_path)/dist

  - task: AzureStaticWebApp@0
    displayName: 'Deploy to Azure Static Web App'
    inputs:
      cwd: '$(angular_project_path)'
      app_location: '/'
      skip_app_build: true
      skip_api_build: true
      output_location: 'dist/admin-client/browser'
    env:
      azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
